# Generated by Django 5.0.6 on 2024-06-18 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_code',
            field=models.CharField(default=1, max_length=200, verbose_name='Kategoriya kodi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='category_name',
            field=models.CharField(default=1, max_length=200, verbose_name='Category Nomi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory_code',
            field=models.CharField(default=1, max_length=34, verbose_name='Ost-kategoriya kodi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory_name',
            field=models.CharField(default=1, max_length=30, verbose_name='Ost-kategoriya nomi'),
            preserve_default=False,
        ),
    ]
