# Generated by Django 5.0.6 on 2024-06-18 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeleUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, null=True, verbose_name='Full Name')),
                ('username', models.CharField(max_length=30, null=True, unique=True, verbose_name='Username')),
                ('telegram_id', models.PositiveBigIntegerField(unique=True, verbose_name='Telegram Id')),
            ],
        ),
    ]
